Eppo-exp/python-sdk

eppo_client/client.py, eppo_client/configuration_requestor.py, test/client_test.py
---
---
Use the new `overrides` field from the RAC response to return variation overrides.
=> Implement allow list

eppo_client/__init__.py, eppo_client/client.py, eppo_client/config.py, test/client_test.py
---
---
Fixes Eppo-exp/eppo#3871
Fixes Eppo-exp/eppo#3879
Currently, the experiment has to be enabled for the allow list to work. But the allow list should work regardless of the experiment status or traffic allocation, since it is used for QA.
Do the allow list override check as the first part of the assignment function.
Added unit test
=> Allow assigning subject from overrides when experiment is not enabled

eppo_client/__init__.py, eppo_client/rules.py, test/rules_test.py
---
---
Fixes https://github.com/Eppo-exp/eppo/issues/4146
Same changes as https://github.com/Eppo-exp/js-client-sdk/pull/6 but for Python
=> OneOf operator should be case insensitive

eppo_client/__init__.py, eppo_client/configuration_requestor.py, eppo_client/http_client.py
---
---
Fixes: #4791
[See Slack thread](https://eppo-group.slack.com/archives/C035Z4W1LJZ/p1663355094784249)
To make the SDK poller more resilient to transient failures, exceptions should not stop the polling task. 
=> Handle exceptions in polling task

eppo_client/__init__.py, setup.cfg
---
---
Need to pin the Pydantic version in setup.cfg to ensure pip does not install pydantic 2 (which is currently incompatible with the SDK)
Locally by running the package build
=> Pin Pydantic version to v1.* in setup.cfg

eppo_client/variation_type.py, test/client_test.py
---
---
Noticed this yesterday:
=> Fix get_numeric_assignment for boolean feature flag, should return None

eppo_client/__init__.py, eppo_client/assignment_logger.py, eppo_client/base_model.py, eppo_client/client.py, eppo_client/config.py, eppo_client/configuration_requestor.py, eppo_client/rules.py, eppo_client/variation_type.py, requirements.txt, setup.cfg, test/client_test.py
Our customers are upgrading to pydantic 2; we need to in order to unblock them.
Following the migration guide (https://docs.pydantic.dev/2.0/migration/) and used the `bump-pydantic` tool to generate changes.
Unit tests initially failed; continued working on the PR until they were all ✅ 
=> upgrade to pydantic 2.3 (FF-957)

eppo_client/__init__.py, eppo_client/client.py, eppo_client/config.py, test/client_test.py
---
---
Add protection for exceptions in our SDKs from bubbling out to our customers' applications by wrapping all public methods in a try/catch.
* `is_graceful_mode` is on by default - this is prevent exceptions, expect for `ValueError` from bubbling up as this is the way python performs validation. we throw this exception if the `flagKey` is not set in `validate_not_blank`
* Add tests for mode on and off
=> add try except to all public client methods (FF-947)

eppo_client/client.py, eppo_client/eval.py, eppo_client/rules.py, test/client_test.py, test/eval_test.py, test/rules_test.py
=> Python UFC SDK updates

eppo_client/configuration_store.py, test/configuration_store_test.py
---
---
Fixes: #ff-1989
We need to ensure flags that are no longer in the config are removed when updating the configuration
Clear the configuration store before loading new flags
Added a unit test
=> [UFC] Clear config store before loading new config

eppo_client/__init__.py, eppo_client/configuration_store.py, test/configuration_store_test.py
---
---
A bug was fixed in the `3.x.y` branch (https://github.com/Eppo-exp/python-sdk/pull/39/commits/435e7f0e19f6c7cd4497a8c641f61052b9205281) but is effecting customers in the `1.x.y` branch. We need to make a new release at `1.x.y` to make it available for those not ready to upgrade to 3.
Create a new release branch:
```
➜  python-sdk git:(heads/main) git checkout -b release/1.3.2 v1.3.1
Switched to a new branch 'release/1.3.2'
```
We will publish from this branch and it is the base of this PR.
Created a branch from it and cherry-picked the changes + version bump:
```
➜ …
```
=> backporting fix to stale configuration cache to `v1.x.y` branch

setup.cfg
---
labels: bugfix
---
Fixes: N/A. Can create an issue if needed.
Whenever I install the new SDK into a fresh Python environment, I encounter the error `ModuleNotFoundError: No module named 'semver'` whenever running `import eppo_client`. Running a `pip install semver` fixes the issue`. 
Just added `semver` to the `install_requires` list. 
I created a fresh Python virtual environment and installed from this branch with `pip install git+https://github.com/Eppo-exp/python-sdk.git@tyler/add-semver-dependency`. After doing that, I can run `import …
=> Added semver dependency

example/.env.dist, example/01_script.py, example/02_fastapi.py, example/03_bandit.py, example/README.md, example/requirements.txt
Updates our examples, adds a FastAPI example and a bandit example
Updated the examples/ folder to add additional examples.
Runs locally
=> Update SDK usage examples

.github/workflows/publish.yml
---
---
* github actions deprecated
* signing package failing: https://github.com/Eppo-exp/python-sdk/actions/runs/9214277452/job/25350163988
Publish `1.3.3` successfully, including signing: https://github.com/Eppo-exp/python-sdk/actions/runs/9214669277
=> Upgrade to latest github packages to fix publish command. (#41)

eppo_client/configuration_requestor.py
Noticed an extra print statement that we don't need. Removing it
=> remove unneeded print statement

eppo_client/rules.py
`json.dumps` is slow, and integers can be common, so convert them using `str` instead for better performance
in to_string, add an explicit conversion for integers
tests still pass
=> [ufc] to_string: handle integers explicitly for better performance

eppo_client/bandit.py, eppo_client/client.py, eppo_client/eval.py, eppo_client/rules.py, eppo_client/types.py, test/client_bandit_test.py
Fixes: #ff-2397
Currently, users need to specify numerical and categorical attributes explicitly. This adds an option to supply a dictionary and we do the conversion to numerical and categorical attributes within the SDK based on value types
- Allow users to give subject and action attributes as dicts
- If needed, convert these dicts to attributes
- Changed the types for this pattern to look clean
- Turn off graceful mode for tests to catch errors explicitly
All tests pass
[//]: # (Add one or multiple labels: enhancement, refactoring, …
=> [ff-2397] Allow attributes to be specified as dicts

.github/workflows/publish.yml, README.md
---
---
Publish with signing fails because at that step the release has already been made; it attempts to create another one: https://github.com/Eppo-exp/python-sdk/actions/runs/9945729712/job/27474683642
This seems to only happen to me because I'm used to creating a Github release like in the other SDKs. If just pushing to a tag without a release the process likely works.
* Combine the two publishing steps (publishing and publishing with signing) into one.
* Add readme for developers.
Difficult to test: suggestions …
=> bug: [Consolidate publishing and signing distributions into one step]

eppo_client/bandit.py
🎟️ Fixes: FF-3060
👯 Universal Test PR: [sdk-test-data/52](https://github.com/Eppo-exp/sdk-test-data/pull/52)
Tie-breaker by action name was introduced to the bandit evaluation algorithm to eliminate ambiguity when multiple actions are the top scoring
- Selects top scoring action by score then by action key
Universal tests
=> fix: Use action key to select best scoring action

eppo_client/version.py
bump to v3.5.2 to pick up high-score tie-breaking.
=> Bump version patch #

eppo_client/client.py, eppo_client/version.py, test/client_bandit_test.py, test/client_test.py
---
---
This fixes timestamps, so they get properly serialized with timezone information.
```
>>> datetime.datetime.now(datetime.timezone.utc).isoformat()
'2024-08-20T17:58:45.374349+00:00'
>>> datetime.datetime.utcnow().isoformat()
'2024-08-20T18:01:31.482134'
```
Not tested.
=> fix: add timezone to timestamps

eppo_client/client.py, eppo_client/version.py
---
---
`|` on dicts is only available with Python-3.9+. Using Python-3.8 or lower, tests fail
Replace `|` with unpacking.
Run tests with Python 3.8.3
=> fix: `|` on dicts is only available with Python-3.9+

README.md, eppo_client/assignment_logger.py, eppo_client/client.py, eppo_client/config.py, eppo_client/version.py, requirements-test.txt, requirements.txt, setup.cfg, test/cache_assignment_logger_test.py
---
---
Fixes: https://linear.app/eppo/issue/FF-3143/%5Bpython%5D-deduplication-cache-for-assignment-and-bandit-events
This allows deduplicating assignments and bandit actions before they are logged to client storage.
This PR adds a caching logger adapter that optionally accepts caches for assignment and bandit. Cache implementation can be any `MutableMapping`:
- Any instance of `Cache` from `cachetools` (with any configuration)
- `dict` for non-evicting (unbound) cache (not recommended)
If cache is not provided for assignment or bandits, that type of events is not cached.
This design decouples …
=> FF-3143 feat: add caching logger for assignment and bandit events

README.md, eppo_client/__init__.py, eppo_client/client.py, eppo_client/config.py, eppo_client/configuration.py, eppo_client/configuration_requestor.py, eppo_client/configuration_store.py, eppo_client/models.py, eppo_client/version.py, test/client_no_poller_test.py, test/configuration_test.py, test/initial_configuration_test.py
---
---
Fixes: https://linear.app/eppo/issue/FF-3150/%5Bpython%5D-allow-python-sdk-to-be-bootstrapped-from-configuration
- Add `Configuration` class that can be initialized from a JSON-serialized flags configuration: `Configuration(flags_configuration="{…}")`
- Add `initial_configuration: Optional[Configuration]` field to `Config` which initializes configuration store with this value.
- Make `poll_interval_seconds` `Optional[int]` (allow `None`), which disables polling
[//]: # (Add one or multiple labels: enhancement, …
=> FF-3150 feat: allow passing initial_configuration
